export const data = [
    {
        id: 1,
        name: "Portfolio template",
        description: "A Portfolio template built with HTML, SCSS and Javascript",
        image: "/port-temp.png",
        status: "Completed",
        technology: ["HTML", "SCSS", "JAVASCRIPT"],
        github: "https://github.com/JUNNY12/portfolio_template",
        deployed: "https://doe-temp.netlify.app/dist/",
    },

    {
        id: 2,
        name: "Furnical",
        description: "An ecommerce furniture web app built with strapi and redux",
        image: "/furnical.png",
        status: "Completed",
        technology: ["REACT", "REDUX", "STYLED-COMPONENT"],
        github: "https://github.com/JUNNY12/furnical",
        deployed: "https://furnical.vercel.app/",
    },

    {
        id: 3,
        name: "Incident Reporting",
        description: "A web app that allows users to report incidents",
        image: "/reporting.png",
        status: "Completed",
        technology: ["REACT + TYPESCRIPT", "FIREBASE", "TAILWIND"],
        github: "https://github.com/JUNNY12/Incident-reporting",
        deployed: "https://incident-reporting.vercel.app/",
    },
    {
        id: 4,
        name: "Whitespace",
        description: "A modern landing page built with HTML, SCSS and Javascript",
        image: "/whitepace.png",
        status: "Completed",
        technology: ["HTML", "SCSS", "JAVASCRIPT"],
        github: "https://github.com/JUNNY12/white_space",
        deployed: "https://white-pace.netlify.app/dist/",
    },
    {
        id: 5,
        name: "Expense Manager",
        description: "A web app to track your expenses",
        image: "/expense.png",
        status: "Completed",
        technology: ["REACT", "FIREBASE", "REACT-BOOSTRAP"],
        github: "https://github.com/JUNNY12/expense_manager",
        deployed: "https://expense-manager-tau-two.vercel.app",
    },
    {
        id: 6,
        name: "Booke",
        description: "An Online Book store",
        image: "/booke.png",
        status: "ongoing",
        technology: ["NEXT JS", "FIREBASE", "TAILWIND"],
        github: "https://github.com/JUNNY12/booke",
        deployed: "https://booke-me.vercel.app",
    },
    {
        id: 7,
        name: "Chatter",
        description: "An Online platform to post article content",
        image: "/chatter.png",
        status: "Completed",
        technology: ["REACT JS", "FIREBASE", "TAILWIND"],
        github: "https://github.com/JUNNY12/chatterapp",
        deployed: "https://chattermd.vercel.app/",
    },
];